on:
  push:
  # schedule:
  #   - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  pages: write

concurrency:
  group: build
  cancel-in-progress: false

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: SereinCommunity/gallery-builder
          path: gallery-builder

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: |
          cd gallery-builder
          pnpm i

      - name: Build
        run: |
          cd gallery-builder
          pnpm run start -p ../
        env:
          TOKEN: ${{ github.token }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: gallery-builder/output

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: gallery-builder/output/gallery

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: SereinCommunity/sereincommunity.github.io
          path: docs
          token: ${{ secrets.TOKEN }}

      - name: Copy gallery
        run: |
          Copy-Item gallery-builder/output/website/* docs/plugins/ -Recurse -Force

      - name: Get Time
        id: time
        uses: nanzm/get-time-action@master
        with: 
          format: 'YYYY-MM-DD HH:mm'

      - name: Commit & Push changes
        uses: actions-js/push@master
        continue-on-error: true
        with:
          github_token: ${{ secrets.TOKEN }}
          message: "[${{ steps.time.outputs.time }}] Update gallery"
          directory: docs
          repository: SereinCommunity/sereincommunity.github.io
