on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x

      - uses: ./.github/actions/download
        with:
          token: ${{github.token}}

      - name: Run ExtensionsHelper
        run:
          ./ExtensionsHelper.exe --version
          ./ExtensionsHelper.exe check ./ -a -t ${{github.token}}

