on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint-md:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: lint-md-github-action
        uses: lint-md/github-action@v0.1.1
