on:
  push:
  workflow_dispatch:

jobs:
  generate-index:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x

      - uses: ./.github/actions/download
        with:
          token: ${{github.token}}

      - name: Run ExtensionsHelper
        run: ./ExtensionsHelper.win-x64.exe gen-index ./ -a -t ${{github.token}}

  # generate-docs:
  #   runs-on: windows-latest

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Install .NET
  #       uses: actions/setup-dotnet@v4
  #       with:
  #         dotnet-version: 7.0.x

  #     - name: Download latest ExtensionsHelper
  #       uses: robinraju/release-downloader@v1.9
  #       with:
  #         repository: SereinDev/ExtensionsHelper
  #         preRelease: true
  #         fileName: ExtensionsHelper.win-x64.exe

  #     - name: Run ExtensionsHelper
  #       run: ./ExtensionsHelper.win-x64.exe gen-docs ./ -a -t ${{github.token}}
